### ISSUE TITLE
Error: libcudnn_ops_infer.so.8

### ISSUE THREAD

**Issue by asdrabael** [daswer123/xtts-finetune-webui#31]
I have cuDNN 8, I can find it by searching my directorys. its both in torch and in the nvidia cudnn folder, but I just get this error when I try to create a dataset:

To create a public link, set `share=True` in `launch()`.
Existing language matches target language
Loading Whisper Model!
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Aborted (core dumped)

I have it running in a venv that's using python 3.9 and have installed the requirements.txt as well as torch==2.1.1+cu118 torchaudio==2.1.1+cu118 and this error is driving me nuts. Any help would be appreciated.

**Comment by Wilkuuu** [comment]
check here
https://github.com/SYSTRAN/faster-whisper/issues/516
you need install libs 

https://stackoverflow.com/questions/66977227/could-not-load-dynamic-library-libcudnn-so-8-when-running-tensorflow-on-ubun
here if you use ubuntu 
sudo apt install nvidia-cudnn

**Comment by asdrabael** [comment]
That fixed it, thanks. it's so strange that the cuDNN library isn't part of the nvidia toolkit.
