### ISSUE TITLE
Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}

### ISSUE THREAD

**Issue by Wilkuuu** [daswer123/xtts-finetune-webui#81]
Existing language matches target language
Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
./start.sh: line 8:  8680 Aborted                 (core dumped) python xtts_demo.py

any ideas? i reinstall cuda, drivers, venv

**Comment by rvuyyuru2** [comment]
same here

**Comment by rvuyyuru2** [comment]
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=11&target_type=deb_network installed cuda setup ?, https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Debian&target_version=12&target_type=deb_network

**Comment by Wilkuuu** [comment]
yes, same issue

**Comment by Wilkuuu** [comment]
i even try rollback to previous version but ... nope...

**Comment by rvuyyuru2** [comment]
it worked for me

**Comment by Wilkuuu** [comment]
What works?

**Comment by lainedfles** [comment]
There's a deep **TTS** module dependency chain (pytorch) that is limited cudnn to 8. Sadly, [the upstream project has ceased development](https://github.com/coqui-ai/TTS/issues/3488) because Coqui has shut down.

Until there's a better option (https://github.com/idiap/coqui-ai-TTS looks promising), your best option is to use docker or podman.

**Comment by mommalicious** [comment]
same problem. Tho it says 'Warning, existing language does not match target language. Updated lang.txt with target language.' on first line. 

Is there really no workarounds here?

**Comment by DravenHawk** [comment]
i ran:

'pip install ctranslate2==4.4.0'

then

'sudo apt-get install libcudnn8 && sudo apt-get install libcudnn8-dev'

and this worked for me

**Comment by Bartabok** [comment]
> i ran:
> 
> 'pip install ctranslate2==4.4.0'
> 
> then
> 
> 'sudo apt-get install libcudnn8 && sudo apt-get install libcudnn8-dev'
> 
> and this worked for me

sudo is for Unix no ? and solution for Windows ?
I'm still stuck with the same problem. Can't find a way to run xtts-finetune-webui
