### ISSUE TITLE
Could not locate cudnn_ops64_9.dll. Please make sure it is in your library path!

### ISSUE THREAD

**Issue by Codex-xD** [daswer123/xtts-finetune-webui#88]
cudnn error when creating a new dataset. I am not a coding guy but have installed cudnn & tensorflow(maybe it was needed IDK) using pip installer. 

Error:
Could not locate cudnn_ops64_9.dll. Please make sure it is in your library path!

Also before the server starts it says: INFO: Could not find files for the given pattern(s).

**Comment by Codex-xD** [comment]
> Same issue here. I've read in this [post](https://github.com/SYSTRAN/faster-whisper/issues/1080) that the dll error indicates a version mismatch. But they have not mentioned the required version of cuDNN.

I fixed it by following this video https://youtu.be/ctQi9mU7t9o Hope it helps!

**Comment by MarcGaumont** [comment]
Same issue, i see it when i do a where on the dll ... yet still not working
